# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Swift
      uses: compnerd/gha-setup-swift@main
      with:
        branch: swift-5.10-release
        tag: 5.10-RELEASE
    - name: Build
      run: swift build -v
